### ISSUE TITLE
Component can't be downloaded from vaadin-addons due wrong project structure

### ISSUE THREAD

**Issue by Skrikjo** [vaadin/component-starter-flow#108]
Subproject game-card-flow have a dependency on parent, but when we do zip for directory, parent is not included in zip. So after component is uploaded to directory and published to vaadin-addons, it cann't be downloaded as parent is missing in vaadin-addon repository.

Here is error, when I try to use this dependency in other project.
```
[INFO] BUILD FAILURE
...
[ERROR] Failed to execute goal on project sboot-v14rc6: Could not resolve dependencies for project
 com.packagename.myapp:sboot-v14rc6:jar:2.0-SNAPSHOT: Failed to collect dependencies at
 org.vaadin.artur:game-card-flow:jar:0.0.1: Failed to read artifact descriptor for 
org.vaadin.artur:game-card-flow:jar:0.0.1: Failure to find org.vaadin.artur:game-card-flow-parent:pom:0.0.1 
in https://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be 
reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
```

That is not happening for developer of component as while making a zip we install a parrent to our locale repository, but if you remove parent and component from local repo and try to download it from vaadin-addon repo you'll see error from above. 

Here is this component published to directory: https://vaadin.com/directory/component/game-card-add-on

How to reproduce:
Import  dependency to new V14 project and run `mvn install`
```
<dependency>
   <groupId>org.vaadin.artur</groupId>
   <artifactId>game-card-flow</artifactId>
   <version>0.0.1</version>
</dependency>

<repository>
   <id>vaadin-addons</id>
   <url>http://maven.vaadin.com/vaadin-addons</url>
</repository>
```

**Comment by mehdi-vaadin** [comment]
As component-starter-flow is a single-module project with no parent, this issue is not valid anymore and can be closed.
