### ISSUE TITLE
updating 23.2.0 failed. 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/component-starter-flow#369]
frontend build failed when updating vaadin 23.2.0 

step to reproduce:
- take the default branch
- update `vaadin.version` to `23.2.0`
- run `mvn install -Pproduction`

Error:

![image](https://user-images.githubusercontent.com/31067185/188419511-6a0253bd-7c32-4185-94e2-4c49ebeaea43.png)

**Comment by mshabarov** [comment]
Here is a patch to upgrade to 23.2 https://github.com/vaadin/component-starter-flow/pull/370. Have to be `<vaadin.version>23.2.1</vaadin.version>` once it's released.

UPD: I also pin `lit-html` to `2.3.1` because otherwise `1.4.1` is used which has a conflicts in API.
