### ISSUE TITLE
Add provided scope to the vaadin dependencies

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/component-starter-flow#442]
An addon is supposed to work in a Vaadin project so the library should be provided by the main project. (So maven doesn't need to omit one particular version of Vaadin).
So I think we should add the scope you can also do it on flow-client...)
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-core</artifactId>
            <scope>provided</scope>
        </dependency>
```

Or am I mistaken?

**Comment by mshabarov** [comment]
This makes sense and sounds good to me, let's do it.
